// Main game configuration file

// Logger settings
log.enabled: true;
log.level: "debug";
log.toStdout: true;
log.timestampTags: false;
log.levelTags: true;

// VFS settings
vfs.appDataFolder: ".ruins_of_hell";

// Window settings (used in windowed mode)
window.display: 0;
window.width: 0;
window.height: 0;
window.x: "auto";
window.y: "auto";
window.maximized: false;
window.resizable: true;
window.hiDPI: true;
window.title: "Ruins of Hell 1.0";

// Display settings
fullscreen: false;
vsync: 1;
stepFrequency: 60;
hideConsole: false;

// Locale settings
locale: "en_US";

// OpenGL settings
gl.debugOutput: false;
gl.outputColorProfile: "sRGB";
gl.anisotropicFiltering: true;
gl.defaultTextureAnisotropy: 16;
gl.shaderCache.enabled: false;
